services:
  swagger-ui:
    build:
      context: .
      dockerfile: Dockerfile-spec
    ports:
      - "80:8080"
    depends_on:
      - app
    networks:
      interface_net:

  db:
    image: postgres:16-alpine
    expose:
      - 5432
    environment:
      POSTGRES_DB: subscription_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app_net:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: ./configs/local.yaml
      DB_PASS: password
    volumes:
      - app_configs:/usr/local/src/configs
    depends_on:
      - db
    command:
      - ./app
    networks:
      interface_net:
      app_net:

volumes:
  postgres_data:
  app_configs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./configs

networks:
  app_net:
  interface_net:
