services:
  swagger-ui:
    build:
      context: .
      dockerfile: Dockerfile-spec
    ports:
      - "80:8080"
    environment:
      - SWAGGER_JSON=/api/bundle.yaml

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: subscription_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: