env: dev

db:
  host: 172.20.0.2
  port: 5432
  database: subscription_service
  user: user
  ssl_mode: disable

server:
  # Основные настройки
  port: 8080
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "30s"
  shutdown_timeout: "10s"

  middleware:
    # Logger
    logger:
      enabled: true

    # Recovery
    recovery:
      enabled: true

    # Timeout
    timeout:
      enabled: true
      duration: "30s"
