env: local

db:
  host: 172.20.0.2
  port: 5432
  database: subscription_service
  user: user
  ssl_mode: disable

server:
  # Основные настройки
  address: ":8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  shutdown_timeout: "10s"

  # Middleware настройки
  middleware:
    # Logger
    logger:
      enabled: true
      format: "text"

    # Recovery
    recovery:
      enabled: true
      stack_size: 1024

    # Timeout
    timeout:
      enabled: true
      duration: "30s"

    # Rate Limiting
    rate_limit:
      enabled: true
      requests: 100
      window: "1m"
      burst: 50
