env: local

db:
  host: db
  port: 5432
  database: subscription_service
  user: user
  ssl_mode: disable

server:
  # Основные настройки
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  shutdown_timeout: "10s"

  # Middleware настройки
  middleware:
    # Logger
    logger:
      enabled: true

    # Recovery
    recovery:
      enabled: true

    # Timeout
    timeout:
      enabled: true
      duration: "30s"
