parameters:
  LimitParam:
    name: limit
    in: query
    schema:
      type: integer
      format: int64
      default: 10
  OffsetParam:
    name: offset
    in: query
    schema:
      type: integer
      format: int64
      default: 0

  IdUserParam:
    name: id
    in: path
    required: true
    schema:
      type: string

  IdSubParam:
    name: id
    in: path
    required: true
    schema:
      type: number

  StartDateParam:
    name: start_date
    in: query
    description: Start of subscription
    schema:
      type: string
      format: date
      example: "2024-01-01"

  EndDateParam:
    name: end_date
    in: query
    description: End of subscription
    schema:
      type: string
      format: date
      example: "2024-01-01"

  SubNameParam:
    name: sub_name
    in: query
    description: subscription name
    schema:
      type: string
